cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('users.urls', namespace='users')),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('django.contrib.auth.urls')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.conf import settings

app_name = 'shop'

urlpatterns = [
    path('product_list/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('product/create/', views.product_new, name='product_new'),
    path('product/<int:pk>/edit/', views.product_edit, name='product_edit'),
    path('product/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('category/create/', views.category_new, name='category_new'),
    path('category/<int:pk>/edit/', views.category_edit, name='category_edit'),
    path('category/view/', views.category_list, name='category_list'),
    path('category/<int:pk>/delete/', views.category_delete, name='category_delete'),
    path('shop/employee_home/', views.employee_home, name='employee_home'),
    path('shop/home/', views.home, name='home'),
    path('shop/contact_page/', views.visitor_new, name='visitor_new'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_list_by_category',
                           args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_detail',
                           args=[self.id, self.slug])


class Feedback(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    subject = models. CharField(max_length=100)
    description = models.CharField(max_length=500)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Product, Category, Feedback
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'name', 'slug', 'image', 'description', 'price', 'available')


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'slug')

class VisitorForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('name', 'email', 'subject', 'description')

shop/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.utils import timezone
from .filter import ProductFilter
from .models import Category, Product
from users.models import Customer, User
from orders.models import Order
from cart.forms import CartAddProductForm
from .forms import ProductForm, CategoryForm, VisitorForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    productFilter = ProductFilter(request.GET, queryset=products)
    products = productFilter.qs
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'productFilter': productFilter})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    user = request.user
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'user': user})

@staff_member_required
def product_new(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.created = timezone.now()
            product.save()
            products = Product.objects.filter(created__lte=timezone.now())
            return redirect('shop:product_list')
    else:
        form = ProductForm()
    return render(request, 'shop/product/product_new.html', {'form': form})


@staff_member_required
def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save()
            product.updated = timezone.now()
            product.save()
            products = Product.objects.filter(created__lte=timezone.now())
            return redirect('shop:product_list')
    else:
        form = ProductForm(instance=product)
    return render(request, 'shop/product/product_edit.html', {'form': form})

@staff_member_required
def category_new(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.save()
            return redirect('shop:category_list')
    else:
        form = CategoryForm()
    return render(request, 'shop/category/category_new.html', {'form': form})

@staff_member_required
def category_edit(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save()
            category.save()
            return redirect('shop:category_list')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'shop/category/category_edit.html', {'form': form,
                                                                'pk': pk})


@staff_member_required
def employee_home(request):
    categoryCount = str(Category.objects.all().count())
    productsCount = str(Product.objects.all().count())
    customerCount = str(Customer.objects.all().count())
    orderCount = str(Order.objects.all().count())
    context = {"categoryCount": categoryCount,
               "productsCount": productsCount,
               "customerCount": customerCount,
               "orderCount": orderCount}

    return render(request, 'shop/employee_home.html', {'context': context})


def category_list(request):
    categories = Category.objects.all()
    return render(request, 'shop/category/categories_list.html',
                  {'categories': categories})

@staff_member_required
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        category.delete()
        return redirect('shop:category_list')
    return render(request, 'shop/category/category_delete.html', {'category': category})

@staff_member_required
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        product.delete()
        return redirect('shop:product_list')
    return render(request, 'shop/product/product_delete.html', {'product': product})


def home(request):
    if request.user.is_staff:
        return redirect('shop:employee_home')
    elif request.user.username:
        return redirect('shop:product_list')
    else:
        return redirect('users:home')


def visitor_new(request):
    if request.method == "POST":
        form = VisitorForm(request.POST)
        if form.is_valid():
            visitors = form.save(commit=False)
            visitors.created_date = timezone.now()
            visitors.save()
            return render(request, 'shop/feedback_done.html')

    else:
        form = VisitorForm()
        # print("Else")
    return render(request, 'shop/contact_page.html', {'form': form})

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div id="product-detail">
    <div id="product-detail-img-container">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
    </div>
  <div id="product-detail-description">
    <h1>{{ product.name }}</h1>
    <label>Description :</label> <div>{{ product.description|linebreaks }}</div>
    <h4><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h4>
    <p class="price">${{ product.price }}</p>

    <form action="{% url "cart:cart_add" product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      {% if user.is_staff %}
          <div class="product-update-options">
              <a class="btn btn-primary" href="{% url 'shop:product_edit' pk=product.pk %}">Edit product</a>
              <a class="btn btn-danger" href="{% url 'shop:product_delete' pk=product.pk %}">Delete</a>
          </div>
      {% else %}
          <input type="submit" value="Add to cart">
      {% endif %}
    </form>

  </div>
  </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    <form method="GET" class="filter-form" id="product-filter">
      <span class="glyphicon glyphicon-filter"></span><span><b>Filters : </b></span>
        <div>
      {{ productFilter.form }}
      <input type="submit" value="Filter" class="btn btn-default"/>
        <input  type="submit" value="Clear" class="btn btn-default" onclick="resetform()">
    </div>
    </form>
    {% for product in products %}
      <div class="item">
        <div class="product-img-container">
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
            </a>
        </div>
      <div class="product-name">
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
            ${{ product.price }}
      </div>
      </div>
{#        <div class="card-columns">#}
{#        <div class="card-body">#}
{#            <a href="{{ product.get_absolute_url }}">#}
{#                <img src="{% if product.image %}{{ product.image.url }}#}
{#                          {% else %}{% static "img/no_image.png" %}{% endif %}">#}
{#            </a>#}
{#        </div>#}
{#        <div class="card-text">#}
{#            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>#}
{#                ${{ product.price }}#}
{#        </div>#}
{#      </div>#}
    {% endfor %}
  </div>
{% endblock %}

shop/templates/shop/product/product_delete.html
<!DOCTYPE html>
<html lang="en">
{% extends 'shop/base.html' %}
{% block content %}
    <h1 class='headings' >Delete product</h1>
    <form method="post" class="custom-form">
        {% csrf_token %}
        <h4>Are you sure you want to delete the category : <b>{{ product.name }}</b></h4>
        <h5><span class="glyphicon glyphicon-warning-sign"></span> Attention !!! This action cannot be undone and you will lose the data forever!</h5>
        <div class="buttons-container">
            <input type="submit" class="btn btn-danger" value="Delete">
            <a href="{% url 'shop:product_list'  %}">Cancel</a>
        </div>

    </form>

{% endblock %}

</html>

shop/templates/shop/product/product_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'shop/base.html' %}
{% block content %}
    <h1 class="headings">Edit Product</h1>
    <form method="POST" class="custom-form">{% csrf_token %}
        {{ form.as_p }}
        <div class="buttons-container">
            <button type="submit" class="save btn btn-default">Update</button>
        </div>
    </form>
{% endblock %}
</html>

shop/templates/shop/product/product_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'shop/base.html' %}
{% block content %}
    <h1 class="headings">Add a New Product</h1>
    <form method="POST" class="custom-form" enctype="multipart/form-data">{% csrf_token %}
          {{ form.as_p }}
        <div class="buttons-container">
            <button type="submit" class="save btn btn-default">Save</button>
        </div>
    </form>
{% endblock %}

</html>