cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('users.urls', namespace='users')),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('django.contrib.auth.urls')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('order_list/', views.order_list, name='order_list'),

]

shop/urls.py
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.conf import settings

app_name = 'shop'

urlpatterns = [
    path('product_list/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('product/create/', views.product_new, name='product_new'),
    path('product/<int:pk>/edit/', views.product_edit, name='product_edit'),
    path('product/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('category/create/', views.category_new, name='category_new'),
    path('category/<int:pk>/edit/', views.category_edit, name='category_edit'),
    path('category/view/', views.category_list, name='category_list'),
    path('category/<int:pk>/delete/', views.category_delete, name='category_delete'),
    path('shop/employee_home/', views.employee_home, name='employee_home'),
    path('shop/home/', views.home, name='home'),
    path('shop/contact_page/', views.visitor_new, name='visitor_new'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from . import views
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



app_name = 'users'

urlpatterns = [
    re_path(r'register_customer/', views.register_customer, name='register_customer'),
    path('edit/<int:pk>', views.edit_customer, name='edit_customer'),
    path('customer_list/', views.customer_list, name='customer_list'),
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('about_page/', views.about, name='about'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('faq_page/', views.faq, name='faq'),
    #path('', include('django.contrib.auth.urls')),
    path('password_reset_form/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset_form'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('users/password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

]

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_list_by_category',
                           args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_detail',
                           args=[self.id, self.slug])


class Feedback(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    subject = models. CharField(max_length=100)
    description = models.CharField(max_length=500)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Product, Category, Feedback
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'name', 'slug', 'image', 'description', 'price', 'available')


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'slug')

class VisitorForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('name', 'email', 'subject', 'description')

shop/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.utils import timezone
from .filter import ProductFilter
from .models import Category, Product
from users.models import Customer, User
from orders.models import Order
from cart.forms import CartAddProductForm
from .forms import ProductForm, CategoryForm, VisitorForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    productFilter = ProductFilter(request.GET, queryset=products)
    products = productFilter.qs
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'productFilter': productFilter})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    user = request.user
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'user': user})

@staff_member_required
def product_new(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.created = timezone.now()
            product.save()
            products = Product.objects.filter(created__lte=timezone.now())
            return redirect('shop:product_list')
    else:
        form = ProductForm()
    return render(request, 'shop/product/product_new.html', {'form': form})


@staff_member_required
def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save()
            product.updated = timezone.now()
            product.save()
            products = Product.objects.filter(created__lte=timezone.now())
            return redirect('shop:product_list')
    else:
        form = ProductForm(instance=product)
    return render(request, 'shop/product/product_edit.html', {'form': form})

@staff_member_required
def category_new(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.save()
            return redirect('shop:category_list')
    else:
        form = CategoryForm()
    return render(request, 'shop/category/category_new.html', {'form': form})

@staff_member_required
def category_edit(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save()
            category.save()
            return redirect('shop:category_list')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'shop/category/category_edit.html', {'form': form,
                                                                'pk': pk})


@staff_member_required
def employee_home(request):
    categoryCount = str(Category.objects.all().count())
    productsCount = str(Product.objects.all().count())
    customerCount = str(Customer.objects.all().count())
    orderCount = str(Order.objects.all().count())
    context = {"categoryCount": categoryCount,
               "productsCount": productsCount,
               "customerCount": customerCount,
               "orderCount": orderCount}

    return render(request, 'shop/employee_home.html', {'context': context})


def category_list(request):
    categories = Category.objects.all()
    return render(request, 'shop/category/categories_list.html',
                  {'categories': categories})

@staff_member_required
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        category.delete()
        return redirect('shop:category_list')
    return render(request, 'shop/category/category_delete.html', {'category': category})

@staff_member_required
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        product.delete()
        return redirect('shop:product_list')
    return render(request, 'shop/product/product_delete.html', {'product': product})


def home(request):
    if request.user.is_staff:
        return redirect('shop:employee_home')
    elif request.user.username:
        return redirect('shop:product_list')
    else:
        return redirect('users:home')


def visitor_new(request):
    if request.method == "POST":
        form = VisitorForm(request.POST)
        if form.is_valid():
            visitors = form.save(commit=False)
            visitors.created_date = timezone.now()
            visitors.save()
            return render(request, 'shop/feedback_done.html')

    else:
        form = VisitorForm()
        # print("Else")
    return render(request, 'shop/contact_page.html', {'form': form})

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}My shop{% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="{% static "css/base.css" %}" rel="stylesheet">
  <link href="{% static "css/main.css" %}" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="{% static 'javascript/base.js' %}"></script>
</head>
<body>

    <nav  class="navbar navbar-inverse">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'shop:home' %}">Home</a></li>
            <li><a href="{% url 'users:about' %}">About</a></li>
            <li><a href="{% url 'users:faq' %}">Faq</a></li>
            <li><a href="{% url 'shop:visitor_new' %}">Contact</a></li>
            <li><a href="{% url 'shop:product_list' %}">Shop </a></li>
            <li><a href="{% url 'cart:cart_detail' %}"><span class="glyphicon glyphicon-shopping-cart"></span></a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <i class="glyphicon glyphicon-user"></i>
                            <span>{{ user.username }}</span>
                            <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'users:edit_customer' pk=user.pk %}">Edit profile</a></li>
                            <li><a href="{% url 'password_change' %}">Change password</a></li>
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>

                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
    </nav>

  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

shop/templates/shop/contact_page.html
 {% extends 'shop/base.html' %} 
{% block content %} 
     <h1>BE IN TOUCH</h1>
     <p>If you don't see what you're looking for, or would like us to work with you on a custom design, feel free to be in touch!</p> 
     <form method="POST" class="visitor-form">
         {% csrf_token %} 
         {{ form.as_p }} 

         <input type="submit" class="save btn btn-default">Save</input> 
</form>
  {% endblock %}

shop/templates/shop/employee_home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}

   <body>
   {% if user.is_authenticated %}
       <div class="page-container">
           <h2 class="top-menu">Hello {{ user.username }},</h2>
           <p>Please choose from below options.</p>

       </div>
   {% endif %}
   <div class="content">
       <div class="row">
           <div class="col-md-12">
               <div class="links">
                   <!-- Example row of columns -->
                   <div class="row">
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <div class="thumbnail-heading">
                                   <h3>Categories</h3>
                               </div>
                               <img src="{% static "img/Categories.jpg" %}" id="categories-img" alt="categories"/>
                               <div class="caption">
                                   <h4>Total number of categories : {{ context.categoryCount }}</h4>
                                   <a class="btn btn-primary" href="{% url 'shop:category_new' %}"><span class="glyphicon glyphicon-plus"></span> Add</a>
                                   <a class="btn btn-primary" href="{% url 'shop:category_list' %}"><span class="glyphicon glyphicon-th-list"></span> View list</a>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <div class="thumbnail-heading">
                                    <h3>Products</h3>
                               </div>
                               <img src="{% static "img/Products.jpg" %}" alt="products"/>
                               <div class="caption">
                                   <h4>Total number of products : {{ context.productsCount }}</h4>
                                   <a class="btn btn-primary" href="{% url 'shop:product_new' %}"><span class="glyphicon glyphicon-plus"></span> Add</a>
                                   <a class="btn btn-primary" href="{% url 'shop:product_list' %}"><span class="glyphicon glyphicon-th-list"></span> View list</a>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <div class="thumbnail-heading">
                                    <h3>Customers</h3>
                               </div>
                               <img src="{% static "img/Customers.jpg" %}" alt="customers"/>
                               <div class="caption">
                                   <h4>Total number of customers : {{ context.customerCount }}</h4>
                                   <a class="btn btn-primary" href="{% url 'users:register_customer' %}"><span class="glyphicon glyphicon-plus"></span> Add</a>
                                   <a class="btn btn-primary" href="{% url 'users:customer_list' %}"><span class="glyphicon glyphicon-th-list"></span> View list</a>
                               </div>
                           </div>
                       </div>
                       <div class="col-md-3">
                           <div class="thumbnail">
                               <div class="thumbnail-heading">
                                    <h3>Orders</h3>
                               </div>
                               <img src="{% static "img/Orders.jpg" %}" alt="orders"/>
                               <div class="caption">
                                   <h4>Total number of orders : {{ context.orderCount }}</h4>
                                   <a class="btn btn-primary" href="{% url 'orders:order_list' %}"><span class="glyphicon glyphicon-th-list"></span> View list</a>
                               </div>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
       </div>
   </div>
   </body>

{% endblock %}

</html>

shop/templates/shop/feedback_done.html
{% extends "shop/base.html" %}
{% block title %}Thank you for your valuable feedback!{% endblock %}
{% block content %}
    <h1>Have a great day!</h1>
    <p>If you want to login, click here!<a href ="{% url 'users:home' %}">login here</a></p>
{% endblock %}